/**
 * LUXE FIND - Products Database
 * 
 * This file contains all affiliate products for your website.
 * Products are organized by specific beauty concerns (Anti-Dandruff, Hair Growth, etc.).
 * 
 * HOW TO ADD NEW PRODUCTS:
 * 1. Use product-bot.html to generate product code
 * 2. Paste the generated code inside the products array below
 * 3. Make sure to add a comma after each product object
 */

const products = [
    // --- CATEGORY 1: ANTI-DANDRUFF ---
    {
        "id": "anti-dandruff-6977",
        "title": "Bare Anatomy Anti-Dandruff Shampoo (Salicylic Acid + Piroctone Olamine + Biotin)",
        "price": "₹249",
        "image": "https://m.media-amazon.com/images/I/51pQnOebkoL._SL1000_.jpg",
        "link": "https://amzn.to/4bU1lUG",
        "reviewLink": "bare-anatomy-anti-dandruff.html",
        "category": ["Anti-Dandruff", "Oil Control"],
        "description": "A scientifically formulated anti-dandruff shampoo containing 0.2% Salicylic Acid, Piroctone Olamine, and Biotin to exfoliate dead skin cells, reduce dandruff-causing fungus, and support stronger, healthier hair growth",
        "pros": ["Controls oily scalp effectively", "Contains Salicylic Acid exfoliant", "Affordable budget-friendly option", "Non-drying formula", "High Amazon purchase volume", "Suitable for men and women"],
        "cons": ["May not be strong enough for severe dandruff", "Small 100 ml size at base price", "Requires consistent use for visible results"],
        "rating": 4.1,
        "isFeatured": true,
        "tags": ["Top Rated", "Trending"],
        "bestFor": "Oily Dandruff & Itchy Scalp",
        "strength": "Moderate",
        "keyBenefit": "Removes flakes while controlling excess oil without drying your scalp.",
        "verdict": "Expert Choice",
    },
    {
        "id": "anti-dandruff-1137",
        "title": "L'Oréal Professionnel Scalp Advanced 5-In-1 Leave-In Serum – 90ml",
        "price": "₹2200",
        "image": "https://m.media-amazon.com/images/I/61Uo6RPg0yL._SL1500_.jpg",
        "link": "https://amzn.to/4kEaoLO",
        "category": ["Anti-Dandruff", "Oil Control"],
        "description": "A salon-grade leave-in scalp serum formulated to target five major scalp irregularities including oiliness, discomfort, sweat, impurities and odor for long-lasting scalp freshness and balance.",
        "pros": ["Salon-grade professional formula", "Controls excess oil without drying hair", "Lightweight non-greasy leave-in texture", "Targets sweat and scalp odor", "Suitable for men and women"],
        "cons": ["Premium pricing", "Limited customer reviews", "Not specifically an anti-dandruff medication"],
        "rating": 3.6,
        "isFeatured": false,
        "tags": ["Editor's Choice", "Luxury Pick"],
        "bestFor": "Persistent Oily & Sweaty Scalp",
        "strength": "Strong",
        "keyBenefit": "Professional 5-in-1 scalp therapy that controls oil, sweat, odor and discomfort without daily washing.",
        "verdict": "Highly Rated",
    },

    // --- CATEGORY 2: HAIR GROWTH ---
   {
        "id": "hair-growth-0470",
        "title": "Soulflower Rosemary Lavender Healthy Hair Oil",
        "price": "₹466 (Massive 42% Savings)",
        "image": "https://m.media-amazon.com/images/I/41aCZXKfmpL.jpg",
        "link": "https://amzn.to/4aQgqpz",
        "category": ["Hair Growth"],
        "description": "\"A professional-grade, 100% pure and undiluted cold-pressed hair treatment formulated for scalp revitalization and follicle stimulation. This oil utilizes Carnosic Acid from Spanish Rosemary to repair tissue damage and improve cellular turnover at the root, mimicking the effects of Minoxidil without the chemical side effects. Enriched with Linalyl Acetate (Lavender) to reduce scalp inflammation and a base of Castor and Rice Bran oils to provide essential fatty acids that seal the hair cuticle and prevent breakage.\"",
        "pros": ["Natural DHT Blocker: Rosemary is scientifically recognized for blocking the hormone responsible for male and female pattern baldness.","Maximum Value: The ₹466 Pack of 2 deal offers a 42% saving, making it a high-conversion \"Budget Luxe\" find.","Cold-Pressed Purity: Unlike heat-processed oils, this maintains 100% of its nutrient potency for faster results.","Multi-Action Formula: It doesn't just grow hair; it moisturizes the scalp and repairs damage with Castor and Jojoba oil.","90-Day Results: Provides a clear timeline for users to track baby hair growth on their hairline."],
        "cons": ["Consistency is Key: Requires 3 applications per week for at least 3 months to see visible regrowth; not an overnight fix.","    Strong Scent: The natural, undiluted Rosemary and Lavender scent can be quite herbal/strong for sensitive users.","    Consistency: Being a pure oil blend, it can feel heavy if not washed out properly with a good clarifying shampoo."],
        "rating": 5,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice","Luxury Pick"],
        "bestFor": "Thinning hairlines, patchy hair fall, and dry/itchy scalps.",
        "strength": "Targeted",
        "keyBenefit": "The \"Natural Minoxidil\" that regrows baby hair in 90 days.",
        "verdict": "Expert Choice",
        "ingredients": "Rosemary Oil, Lavender Oil, Castor Oil, Jojoba Oil, Amla, and Vitamin E.",
        "usage": "1. Apply 2-3 ml to damp hair/scalp.\n2. Massage in circular motions for 3-5 minutes to boost circulation.\n3. Leave overnight and wash 3 times weekly for 90 days.",
        "whyPicked": "It’s a 100% natural \"Hair Growth Regime\" in a bottle, combining the follicle-stimulating power of Rosemary with the scalp-soothing benefits of Lavender."
    },
   {
        "id": "hair-growth-3607",
        "title": "Pilgrim Spanish Rosemary & Biotin Anti-Hairfall Shampoo",
        "price": "₹274 (10% Off)",
        "image": "https://m.media-amazon.com/images/I/617W5aVW4fL._SL1500_.jpg",
        "link": "https://amzn.to/4aXkV0b",
        "category": ["Hair Growth"],
        "description": "A potent anti-hairfall treatment enriched with Spanish Rosemary (Rosmarinic Acid) to stimulate follicles and Biotin to reinforce the hair shaft, reducing breakage by up to 95%.",
        "pros": ["Natural DHT Blocker 🌿","    Strengthens hair up to 95%","    Stimulates new hair growth","    Budget-friendly Luxe find (₹274)"],
        "cons": ["Needs consistent use for 4 weeks for best results","    Scent might be strong for some"],
        "rating": 4.1,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice"],
        "bestFor": "Hair thinning and excessive breakage.",
        "strength": "Targeted",
        "keyBenefit": "Stop the \"Heartbreak\" of hair fall with the power of Natural DHT Blockers. [cite: 2026-02-23]",
        "verdict": "Expert Choice",
        "ingredients": "Spanish Rosemary, Biotin, Rosmarinic Acid.",
        "usage": "Apply to wet hair.\n    2. Massage deeply into the scalp using fingertips to stimulate blood flow.\n    3. Rinse thoroughly for stronger, cleaner hair.",
        "whyPicked": "6,000+ people bought this last month because it actually blocks the hormone (DHT) responsible for hair loss. [cite: 2026-02-23]"
    },

    // --- CATEGORY 3: OIL CONTROL ---
    {
        "id": "oily-plum",
        "title": "Plum Green Tea Oil-Free Moisturizer",
        "price": "₹470",
        "image": "https://m.media-amazon.com/images/I/51Rv-v+v+v+L._SL1000_.jpg",
        "link": "https://amzn.to/5...",
        "category": ["Oil Control"],
        "description": "Lightweight, matte finish moisturizer with Green Tea extracts to fight acne and control oil.",
        "pros": ["Non-greasy", "Vegan", "Fights breakouts"],
        "cons": ["Small tube"],
        "rating": 4.8,
        "isFeatured": true,
        "tags": ["Top Rated"],
        "bestFor": "Oily/Acne Skin",
        "strength": "Moderate",
        "keyBenefit": "Matte Finish",
        "verdict": "Top Choice",
    },
    {
        "id": "oil-loreal",
        "title": "L'Oreal Scalp Advanced Shampoo",
        "price": "₹750",
        "image": "https://m.media-amazon.com/images/I/51e8E-i-9FL._SL1000_.jpg",
        "link": "https://amzn.to/3...",
        "category": ["Oil Control"],
        "description": "Purifying shampoo with AHAs to reduce 78% of sebum in just one wash.",
        "pros": ["Professional grade", "Intense cleansing", "Refreshing scent"],
        "cons": ["Slightly expensive"],
        "rating": 4.8,
        "isFeatured": false,
        "tags": ["Top Rated"],
        "bestFor": "Extremely Oily Scalp",
        "strength": "Strong",
        "keyBenefit": "Purifies Porous",
        "verdict": "Expert Review",
    },

    // --- CATEGORY 4: ACNE & PIMPLES ---
    {
        "id": "acne-pimples-6861",
        "title": "California Skin+ Anti-Acne Serum",
        "price": "₹285",
        "image": "https://m.media-amazon.com/images/I/61yhN6MeuhL._SL1080_.jpg",
        "link": "https://amzn.to/4qRdehY",
        "category": ["Acne & Pimples"],
        "description": "A concentrated anti-acne treatment featuring 2% Salicylic Acid to exfoliate deep within pores, combined with 4% Niacinamide and Zinc PCA to regulate sebum and strengthen the skin barrier. Includes Licorice and Seaweed extracts to soothe inflammation instantly.",
        "pros": ["Massive 56% discount (Limited Time)", "High 4% Niacinamide for marking fading", "Fragrance-free and Vegan", "Non-greasy, water-like texture"],
        "cons": ["20g is a slightly smaller bottle than standard", "Powerful actives might cause slight purging initially"],
        "rating": 5,
        "isFeatured": false,
        "tags": ["Top Rated", "Luxury Pick"],
        "bestFor": "Active Pimples & Pimple Marks",
        "strength": "Strong",
        "keyBenefit": "Shrinks active acne while fading post-pimple dark spots simultaneously.",
        "verdict": "Expert Choice",
        "ingredients": "2% Salicylic Acid (BHA), 4% Niacinamide, Zinc PCA, Prebiotics Complex, Licorice & Seaweed Extract",
        "usage": "After cleansing, apply 2-3 drops to the entire face or just the affected areas. Gently pat into the skin until fully absorbed. Follow with a lightweight, oil-free moisturizer. Always wear sunscreen during the day when using this serum.",
        "whyPicked": "We picked it because it’s the \"Lowest Price in 30 Days.\" You are getting a premium \"Acne Buster\" complex that usually costs ₹650 for just ₹285. It is the smartest way to upgrade your skincare routine without spending a fortune.",
    },
  
  {
        "id": "oil-control-1230",
        "title": "Cutilift Salicylic Acid 2% Face Wash",
        "price": "₹235",
        "image": "https://m.media-amazon.com/images/I/51ga6J8i7ML._SL1080_.jpg",
        "link": "https://amzn.to/4rW9sVs",
        "category": ["Oil Control","Acne & Pimples"],
        "description": "A deep-cleansing gel formula with 2% Salicylic Acid for exfoliation, Niacinamide for texture improvement, and a botanical blend of Tea Tree and Aloe Vera for a soothing experience.",
        "pros": ["Professional Pharma Grade","    Very affordable (₹235)","    pH Balanced & Non-greasy","    Enriched with soothing Aloe Vera"],
        "cons": ["80ml is a travel-friendly but smaller size","Clinical scent rather than floral"],
        "rating": 4.8,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice"],
        "bestFor": "Deep Cleansing & Oily Skin",
        "strength": "Moderate",
        "keyBenefit": "Clears pores and dissolves excess oil without over-drying the skin.",
        "verdict": "Expert Choice",
        "ingredients": "2% Salicylic Acid, Tea Tree Extract, Aloe Vera, Niacinamide.",
        "usage": "Apply to wet face. 2. Massage gently in circular motions for 60 seconds. 3. Rinse thoroughly with water. Use daily for best results.",
        "whyPicked": "It’s the ultimate budget-friendly professional cleanser. For just ₹235, you get a pH-balanced, clinical formula that rivals expensive luxury brands."
    },
    // --- CATEGORY 5: GLASS SKIN ---
    {
        "id": "glass-skin-/-brightening-6042",
        "title": "L'Oreal Paris Revitalift \"Glass Skin\" Routine (Serum + Gel Cleanser)",
        "price": "₹522",
        "image": "https://m.media-amazon.com/images/I/51077fvCzPL._SL1094_.jpg",
        "link": "https://amzn.to/40prrrA",
        "category": ["Glass Skin / Brightening"],
        "description": "A clinically validated bundle featuring a 50ml Hyaluronic Gel Cleanser and a 15ml 1.5% Hyaluronic Acid Serum. Designed to reduce fine lines by 60% and intensely re-plump the skin.",
        "pros": ["31% Bundle Discount","Visible results in 1 hour","Non-sticky & Lightweight","Fragrance-free & Paraben-free"],
        "cons": ["Small serum bottle (15ml)","Sells out quickly during sales"],
        "rating": 4.8,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice"],
        "bestFor": "Instant Plumping & Monday Morning Glow",
        "strength": "Strong",
        "keyBenefit": "Get the viral \"Glass Skin\" look with this 2-step hydration power duo.",
        "verdict": "Expert Choice",
        "ingredients": "1.5% Hyaluronic Acid (Macro & Micro), Panthenol, Glycerin, Salicylic Acid (low % in cleanser for pore prep).",
        "usage": "1. Massage the Gel Cleanser onto wet face and rinse.\n2. Apply 2-3 drops of the Serum to damp skin.\n3. Tap gently and follow with moisturizer.",
        "whyPicked": "It’s the #1 selling serum in India paired with its perfect cleanser match at a 31% discount—it's a no-brainer for anyone wanting clear, glowing skin by tomorrow."
    },
     {
        "id": "glass-skin-/-brightening-4642",
        "title": "Pilgrim Korean Rice Water Hydra Glow Moisturizer (with 5 Hyaluronic Acids & 3% Niacinamide)",
        "price": "₹241",
        "image": "https://m.media-amazon.com/images/I/613LX1k416L._AC_CR0%2C0%2C0%2C0_SX615_SY462_.jpg",
        "link": "https://amzn.to/4qU9koF",
        "category": ["Glass Skin / Brightening"],
        "description": "A lightweight, quick-absorbing gel cream formulated with Korean Rice Water, 3% Niacinamide, and 5 types of Hyaluronic Acids. Designed to strengthen the skin barrier with 5 Ceramides while providing multi-depth hydration.",
        "pros": ["Instant Glass-Skin Finish","Contains 5 types of Hyaluronic Acids","Lightweight & Non-greasy","Fragrance-free & Vegan"],
        "cons": ["50g Jar might finish quickly if used twice daily","Wait for it to fully dry before applying makeup"],
        "rating": 4.1,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice"],
        "bestFor": "Instant Glass Skin Glow & Deep Pore Hydration",
        "strength": "Strong",
        "keyBenefit": "The K-Beauty secret to a translucent, \"Glass-Like\" glow in a lightweight gel.",
        "verdict": "Expert Choice",
        "ingredients": "Korean Rice Water, 5 Hyaluronic Acids, 3% Niacinamide, 5 Ceramides, Mulberry Extract.",
        "usage": "1. Cleanse with a mild wash. 2. Apply a small amount to the face and neck. 3. Massage in upward circular motions. 4. Use twice daily for the best \"Glass Skin\" results.",
        "whyPicked": "It offers a professional 5-Ceramide barrier repair and a multi-hyaluronic glow for under ₹250. It’s the easiest way to get the \"K-Glow\" without the high price tag."
    },
     {
        "id": "glass-skin-/-brightening-2299",
        "title": "Pilgrim 10% Vitamin C Serum for Glowing Skin",
        "price": "₹527",
        "image": "https://m.media-amazon.com/images/I/71BTAV8rtdL._SL1500_.jpg",
        "link": "https://amzn.to/4s503ed",
        "category": ["Glass Skin / Brightening"],
        "description": "A potent blend of 10% Vitamin C, 5% Niacinamide, and Hyaluronic Acid designed to fade pigmentation and hydrate.",
        "pros": ["Fades dark spots fast, Beginner friendly, Non-greasy formula, Paraben-free"],
        "cons": ["Requires consistent sunscreen use, Scent may be too mild for some"],
        "rating": 4,
        "isFeatured": false,
        "tags": ["Top Rated","Trending"],
        "bestFor": "Dark Spots & Dullness",
        "strength": "Strong",
        "keyBenefit": "Brighter skin in just 5 days ✨",
        "verdict": "Expert Choice",
        "ingredients": "10% Vitamin C, 5% Niacinamide, Hyaluronic Acid, Glycolic Acid",
        "usage": "1. Cleanse face. 2. Apply 3-5 drops to face and neck. 3. Pat gently. 4. Follow with sunscreen.",
        "whyPicked": "It’s an Amazon #1 Best Seller that combines three powerhouse ingredients for under ₹550."
    },

    // --- CATEGORY 6: LIP CARE ---
   {
        "id": "lip-care-3397",
        "title": "SPRING H2O Velvet Hold Matte Liquid Lipstick",
        "price": "₹229",
        "image": "https://m.media-amazon.com/images/I/51gPdIPBGEL._SL1080_.jpg",
        "link": "https://amzn.to/46BXdVY",
        "category": ["Lip Care"],
        "description": "A smudgeproof and waterproof liquid lipstick featuring stay-put pigments and a lightweight, cushiony texture for 12–16 hour comfortable wear.",
        "pros": ["Incredible value (49% off MSRP).","True 12–16 hour staying power.","Completely smudgeproof and mask-friendly.","High-precision applicator for a professional edge."],
        "cons": ["Highly pigmented; requires an oil-based cleanser to remove.","    Matte finish may require a balm base for extremely dry lips."],
        "rating": 4.9,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice"],
        "bestFor": "All-Day Wear & Transfer-Proof Color",
        "strength": "Targeted",
        "keyBenefit": "Bold, velvety color that stays on your lips and off your coffee cup.",
        "verdict": "Expert Choice",
        "ingredients": "Stay-put pigments, Velvet-softening agents, Waterproof polymers.",
        "usage": "1. Outline lips with the precision doe-foot applicator. 2. Fill in with a single stroke. 3. Let it set for 60 seconds for a transfer-proof finish.",
        "whyPicked": "It solves the \"cracked lip\" dilemma. Most long-wear lipsticks feel heavy, but this feels like air while surviving an entire workday and dinner."
    },
      {
        "id": "lip-care-7205",
        "title": "Seoulskin Brightening Lip Balm SPF 50 PA++",
        "price": "₹349",
        "image": "https://m.media-amazon.com/images/I/61HLNYskO0L._SL1500_.jpg",
        "link": "https://amzn.to/4cXo6rb",
        "category": ["Lip Care"],
        "description": "A potent brightening lip treatment formulated with Kojic Acid and Niacinamide to inhibit melanin production while providing heavy-duty SPF 50 protection.",
        "pros": ["Clinical-grade brightening with Kojic Acid.","Maximum UV protection (SPF 50 PA++).","Non-sticky, glossy \"glass skin\" finish.","Repairs the moisture barrier with Ceramides."],
        "cons": ["Only one flavor/scent available (Fruity).","10g tube might run out fast with frequent reapplication."],
        "rating": 4.9,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice"],
        "bestFor": "Dark, Pigmented & Chapped Lips",
        "strength": "Targeted",
        "keyBenefit": "Erase lip pigmentation and reveal your natural pink glow.",
        "verdict": "Expert Choice",
        "ingredients": "Kojic Acid, Niacinamide, Ceramides, SPF 50 PA++, Fruity Extracts.",
        "usage": "1. Apply a generous layer to clean lips. 2. Use 15 minutes before sun exposure. 3. Reapply every 2-3 hours for maximum brightening results.",
        "whyPicked": "Most lip balms just hide the problem; this one actually fixes it. It’s the ultimate \"skincaring\" hack for anyone tired of hiding dark lips under heavy lipstick."
    },

    // --- CATEGORY 7: MAKEUP & SKINCARE ---
     {
        "id": "makeup-skincare-1054",
        "title": "Earth Rhythm Daily Dew Cooling Sunstick SPF 60 PA ++++",
        "price": "₹509",
        "image": "https://m.media-amazon.com/images/I/71kRCWyENhL._SL1500_.jpg",
        "link": "https://amzn.to/4d4Lhj1",
        "reviewLink": "earth-rhythm-sunstick.html",
        "category": ["Makeup & Skincare"],
        "description": "A lightweight, non-comedogenic sunscreen stick that provides broad-spectrum UVA/UVB protection with an invisible, natural finish.",
        "pros": ["Completely invisible finish.","    Non-greasy and lightweight.","    Travel-friendly and mess-free.","    Water-resistant formula."],
        "cons": ["Small 15g size may finish quickly with daily use.","    Requires multiple passes for full coverage."],
        "rating": 4.4,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice"],
        "bestFor": "On-the-go reapplication and makeup wearers.",
        "strength": "Targeted",
        "keyBenefit": "The \"Zero-Trace\" shield that stays invisible even over your makeup.",
        "verdict": "Expert Choice",
        "ingredients": "Uvinul A Plus (Advanced UV Filter), Vitamin E, Avocado Oil, and Jojoba Seed Oil.",
        "usage": "1. Twist the base to reveal the stick.\n2. Glide directly onto face and neck.\n3. Reapply every 2 hours, even over makeup.",
        "whyPicked": "It solves the \"White Cast\" nightmare forever. Perfect for Indian skin tones where traditional sunscreens often look ashy or gray."
    },
    {
        "id": "makeup-skincare-2312",
        "title": "BAKE De-Tan Scrub Treatment Coffee Soap",
        "price": "₹349",
        "image": "assets/bake-de-tan-soap.png",
        "link": "https://amzn.to/4uudNBu",
        "reviewLink": "bake-de-tan-soap.html",
        "category": ["Makeup & Skincare", "Glass Skin / Brightening"],
        "description": "A specialized de-tan treatment soap formulated with 2% Kojic Acid, 1% Glycolic Acid, and 1% Alpha Arbutin to target melanin production and exfoliate dead skin cells.",
        "pros": ["* Visibly reduces tan and pigmentation.","    Real coffee granules for effective exfoliation.","    Pack of 2 offers great value for money.","    Safe for both Face and Body."],
        "cons": ["* Might be slightly drying for very sensitive skin.","    Coffee granules may feel coarse if rubbed too hard."],
        "rating": 4.3,
        "isFeatured": false,
        "tags": ["Top Rated","Trending","Editor's Choice","Luxury Pick"],
        "bestFor": "Stubborn sun tan, dark underarms, and uneven skin texture.",
        "strength": "Targeted",
        "keyBenefit": "Scrub away the tan and reveal brighter skin with the power of Coffee and Kojic Acid.",
        "verdict": "Expert Choice",
        "ingredients": "2% Kojic Acid, 1% Glycolic Acid, 1% Alpha Arbutin, Niacinamide, Natural Coffee Granules.",
        "usage": "1. Wet skin with lukewarm water.\n2. Gently massage the soap bar directly onto tanned areas in a circular motion.\n3. Leave the lather on for 30–60 seconds for the active acids to work.\n4. Rinse thoroughly and pat dry.",
        "whyPicked": "It hits the \"Triple Brightening\" trend—Kojic Acid, Alpha Arbutin, and Niacinamide all in one bar. It’s a \"Salon-Style\" de-tan treatment at a fraction of the cost."
    },
      {
        "id": "glass-skin-brightening-3279",
        "title": "Mamaearth Beetroot Daily Glow Face Cream",
        "price": "₹224",
        "image": "https://m.media-amazon.com/images/I/618F9ahdAIL._SL1500_.jpg",
        "link": "https://amzn.to/4uDyhYl",
        "category": ["Glass Skin / Brightening","Makeup & Skincare"],
        "description": " This dermatologically tested, Made Safe certified cream utilizes the antioxidant properties of Beetroot and the moisture-locking power of Hyaluronic Acid to protect against free radicals while providing long-lasting softness.",
        "pros": ["Gives a natural, hydrated pink glow","Lightweight and non-greasy texture","Provides instant brightening","Made Safe Certified (No toxins)","Keeps skin soft and supple"],
        "cons": ["3.9 rating suggests performance varies by skin tone","May require reapplication for very dry skin","Scent (Beetroot) might be polarizing for some users"],
        "rating": 3.9,
        "isFeatured": false,
        "tags": ["Top Rated","Luxury Pick"],
        "bestFor": " Instant pink glow and daily hydration for all skin types",
        "strength": "Moderate",
        "keyBenefit": " Get a hydrated pink glow and instant brightening in a lightweight, non-greasy formula.",
        "verdict": "Expert Choice",
        "ingredients": "Beetroot Extract\nHyaluronic Acid",
        "usage": "Wash your face with a sulfate-free face wash.\nPat dry and take an adequate amount of cream.\nApply evenly over face and neck.\nGently massage until completely absorbed.",
        "whyPicked": " It bridges the gap between skincare and a glow-booster. We love that it's \"Made Safe\" certified, ensuring that the instant brightening effect comes from natural goodness rather than harsh chemicals"
    },
   {
        "id": "lip-care-1254",
        "title": "Mamaearth Moisture Matte Long Stay Lipstick Minis Gift Set (Bright and Bold)",
        "price": "₹648",
        "image": "https://m.media-amazon.com/images/I/61cLQP4CPLL._SL1200_.jpg",
        "link": "https://amzn.to/3NRXkX6",
        "reviewLink": "mamaearth-lipstick-minis.html",
        "category": ["Lip Care","Makeup & Skincare"],
        "description": "A travel-friendly gift set featuring high-pigment mini lipsticks infused with Avocado Oil and Vitamin E for a comfortable, 8-hour moisture-lock wear.",
        "pros": ["Incredible 12-hour staying power.","    Smudge-proof and transfer-resistant.","    Avocado oil prevents lip cracking/drying.","    Perfectly curated \"Bright and Bold\" shade range for Indian skin tones."],
        "cons": ["* Minis are small (2.1g), though perfect for testing multiple shades.","    Requires a good oil-based cleanser for removal."],
        "rating": 4.2,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice","Luxury Pick"],
        "bestFor": "Long-wear daily use, travel-friendly touch-ups, and premium gifting.",
        "strength": "Targeted",
        "keyBenefit": "12 hours of bold, smudge-proof matte color that actually keeps your lips hydrated.",
        "verdict": "Expert Choice",
        "ingredients": "Avocado Oil, Vitamin E, Rich Matte Pigments.",
        "usage": "1. Start from the center of your upper lip and move outwards.\n2. Repeat on the lower lip for an even, bold finish.\n3. Allow 30 seconds to set for maximum smudge-proof performance.",
        "whyPicked": "It’s the ultimate \"Life-Proof\" lipstick. Whether it's a 12-hour workday or a special occasion, the mini size makes it perfect for the modern woman on the go."
    },
       {
        "id": "anti-dandruff-2233",
        "title": "Indulekha Svetakutaja Ayurvedic Anti-Dandruff Oil",
        "price": "₹306",
        "image": "https://m.media-amazon.com/images/I/61m47CGZeJL._SL1000_.jpg",
        "link": "https://amzn.to/4vRBPHo",
        "reviewLink": "indulekha-svetakutaja-oil.html",
        "category": ["Anti-Dandruff","Hair Growth"],
        "description": ": A clinically proven Ayurvedic medicinal oil formulated with 8 powerful herbs and essential oils, matured under natural sunlight for 7 days to maximize potency.",
        "pros": ["* Clinically proven results in 4 weeks","    Svetakutaja-Comb applicator prevents wastage","    100% natural fragrance and color","    Effective on both mild and severe dandruff"],
        "cons": ["* Strong herbal scent (authentic but intense)","    Needs consistent use to see full results"],
        "rating": 4.2,
        "isFeatured": false,
        "tags": ["Trending","Editor's Choice"],
        "bestFor": "Severe Flakes & Itchy Scalp",
        "strength": "Targeted",
        "keyBenefit": "100% Ayurvedic solution clinically proven to clear dandruff in 4 weeks.",
        "verdict": "Expert Choice",
        "ingredients": "* Svetakutaja (Anti-fungal powerhouse)\n\n    Amla (Vitamin C for scalp health)\n\n    Virgin Coconut Oil (Base nourishment)\n\n    Aloe Vera (Soothing relief)",
        "usage": "1. Attach the Svetakutaja-Comb applicator to the bottle.\n2. Squeeze the bottle and comb directly onto the scalp.\n3. Massage gently with fingertips for 2 minutes.\n4. Leave for 1-2 hours (or overnight) before washing with a mild cleanser.",
        "whyPicked": "We chose this because of its unique 7-day sunlight maturation process. It’s rare to find a budget-friendly oil (₹306) that follows authentic Ayurvedic traditions while being free from parabens, sulfates, and synthetic perfumes."
    },
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = products;
}

















